### PR TITLE
Ignore class field used for implementing the Android Parcelable interface

### PR DESCRIPTION
**Pull request by sebaslogen**
I've made this change to solve this issue https://github.com/LunarWatcher/KClassUnpacker/issues/1

Can you please review it?

### CODE REVIEW

**Comment by LunarWatcher** [comment]
Sorry for the late reply, GH decided not to send me an email for whatever reason it has. 

I'll test it now. A name-based ignoring may not be the best idea, although it's definitely a good idea. Not specifically portable though, so I might modify it slightly. `CREATOR` is probably not the only problematic annotation out there. 

Anyway, I'll merge this as soon as I make it more portable.

**Comment by LunarWatcher** [comment]
Just pushed a commit, and I'd like some feedback before I merge it. 

I haven't done much with parcelable on Android, but a quick search suggests it's a `public static` field. `static` puts it out of the instance, which would explain the issue itself. Anything bound to the instance itself should be linked.

Could you test if this works with the setup you have? If it doesn't work, a specific keyword blacklist would likely be required, which might not be specifically beneficial. (Although grabbing the annotations and checking for any problematic ones and their associated fields would make that better).

**Comment by sebaslogen** [comment]
@LunarWatcher thanks for the fix, your solution is actually much better and will probably remove other unwanted static fields, I've checked the Parcelable case and it's good, so it's good to be merged imho.

Also once you are happy with it, can you also make a new release? Thanks.

**Comment by LunarWatcher** [comment]
Great \o/ Thanks for the initial PR btw ^^ 

As for the release: I've set up the release, it should be built by Jitpack. Either that or it's on the first request, I don't really remember, but the badge suggests it should be up to date. 

<sub>Full disclosure: this is the first project where I've used Jitpack, so I'm not sure about any of that. But according to the page, it should be built when requested, meaning it should be fine now.</sub>

**Pull request merged**
